OUTPUT_DIR: "/home/tvi069/simulation/test/OUTPUT"

SLIM: "/home/tvi069/simulation/test/test.slim" # final VCF output needs to be left blank

LOWCOV_ART: "-ss HS25 -p -l 150 -f 0.5 -m 200 -s 10"
LOWCOV_SAMTOOLS_VIEW: "-q30 -f 0x02"

HIGHCOV_ART: "-ss HS25 -p -l 150 -f 15 -m 200 -s 10"
HIGHCOV_BCFTOOLS_FILTER: "-i 'QUAL >= 50'"

